version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: "UTC"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: /
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "deps"
      include: scope

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: "UTC"
    groups:
      pre-commit-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: /
    labels:
      - dependencies
      - pre-commit
    commit-message:
      prefix: "deps"
      include: scope
